name: "Expression of support"
description: "Express your support for the Cross-Origin Storage API Proposal"
body:
  - type: "markdown"
    attributes:
      value: "# Expression of Support\nFill out this form if you support the **Cross-Origin Storage (COS) API** proposal and would possibly make use of it in your apps."
  - type: "checkboxes"
    attributes:
      label: "What are the primary cross-origin storage use cases in your apps?"
      options:
        - label: "AI models"
        - label: "SQLite databases"
        - label: "Offline storage archives"
        - label: "Wasm modules"
        - label: "Other"
    validations:
      required: true
  - type: "dropdown"
    attributes:
      label: "Would you use this API in production as a progressive enhancement?"
      options:
        - "Yes"
        - "No"
        - "Maybe"
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "Why is cross-origin storage important for your use case?"
      description: "Describe the challenges you face with current solutions and how this API would address them."      
    validations:
      required: true
  - type: "input"
    attributes:
      label: "What company do you work for?"
      description: "If you can share what company you work for, this would help us prioritize the API."
      placeholder: "Example Company, Inc."
    validations:
      required: false
  - type: "textarea"
    attributes:
      label: "Concerns or reservations"
      description: "Do you foresee any potential issues with adopting this API, such as privacy, security, or implementation challenges?"
    validations:
      required: false
  - type: "textarea"
    attributes:
      label: "Additional features or improvements"
      description: "Are there any additional features you'd like to see in the API or any enhancements to its current design?"
    validations:
      required: false
  - type: "textarea"
    attributes:
      label: "Other feedback"
      description: "Is there anything else you want the team to know?"
    validations:
      required: false
